name: PlutoFramework NuGet publish

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
    
jobs:
  publish-plutoframework:
    env:
      BUILD_CONFIG: 'Release'

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install .NET MAUI Workloads (iOS and Android)
      run: dotnet workload install maui maui-ios maui-android

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore dependencies
      run: nuget restore PlutoFramework.sln

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore PlutoFramework.sln

    - name: Build
      run: dotnet build PlutoFramework.sln --configuration Release --no-restore
    
    - name: Publish PlutoFramework
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
       PROJECT_FILE_PATH: ./PlutoFramework/PlutoFramework.csproj
       NUGET_KEY: ${{secrets.NUGET_API_KEY}} 