name: PlutoFramework Unit tests

on:
  workflow_dispatch:
    inputs:
      test_name:
        description: 'Name of the test to run'
jobs:
  plutoframework-tests:
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'PlutoFramework.sln'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.x

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Restore .NET workloads
      run: dotnet workload restore $SOLUTION

    - name: Download tools
      run: dotnet tool install --global StrawberryShake.Tools --version 13.9.12

    - name: Restore
      run: dotnet restore $SOLUTION

    - name: Run tests
      run: |
        if [ -z "${{ github.event.inputs.test_name }}" ]; then
          dotnet test ./PlutoFrameworkTests/PlutoFrameworkTests.csproj
        else
          dotnet test ./PlutoFrameworkTests/PlutoFrameworkTests.csproj --filter "FullyQualifiedName~${{ github.event.inputs.test_name }}"
        fi